name: Push Docker Image on DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
      - uses: actions/checkout@v3
      - name: 'Create env file'
        run: echo "${{ secrets.TWITTER_ENV_PRODUCTION }}" > .env.production
      - name: Build the Docker image
        run: docker build -t namduong0606/twitter:v4 .
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin # Sử dụng --password-stdin
      - name: Push the Docker image
        run: docker push namduong0606/twitter:v4
