name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Create env file'
        run: echo "${{ secrets.TWITTER_ENV_PRODUCTION }}" > .env.production
      - name: Build the Docker image
        run: docker build -t namduong0606/twitter:v4 .
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin # Sử dụng --password-stdin
      - name: Push the Docker image
        run: docker push namduong0606/twitter:v4

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Executing remote ssh commands using password
  #       uses: appleboy/ssh-action@v1.0.0
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.HOST_USERNAME }}
  #         password: ${{ secrets.HOST_PASSWORD }}
  #         port: ${{ secrets.PORT }}
  #         script: |
  #           docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
  #           docker pull namduong0606/twitter:
  #           docker stop twitter-clone
  #           docker rm twitter-clone
  #           docker run -dp 4000:4000 --name twitter-clone --restart unless-stopped
