name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: 'Create env file'
        run: echo "${{ secrets.TWITTER_ENV_PRODUCTION }}" >> .env.production
      - name: Build the Docker image
        run: docker build --progress=plain -t namduong0606/twitter:v1 .
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin # Sử dụng --password-stdin
      - name: Push the Docker image
        run: docker push namduong0606/twitter:v1
