name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: 'Create env file'
        run: echo "${{ secrets.TWITTER_ENV_PRODUCTION }}" >> .env.production
      - name: Build the Docker image
        run: docker build --progress=plain -t namduong0606/twitter:latest .
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push the Docker image
        run: docker push namduong0606/twitter:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pull image from Docker Hub
        run: docker pull namduong0606/twitter:latest

      - name: Delete old container
        run: docker rm -f twitter-container

      - name: Run docker container
        run: docker run -d -p 4000:4000 --name twitter-container namduong0606/twitter:latest
